/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package org.apache.lucene.analysis.tr;

public class FomaWrapper {
  public static SWIGTYPE_p_fsm openFomaFile(String filename) {
    long cPtr = FomaWrapperJNI.openFomaFile(filename);
    return (cPtr == 0) ? null : new SWIGTYPE_p_fsm(cPtr, false);
  }

  public static String findStemWord(String word, SWIGTYPE_p_fsm net) {
    return FomaWrapperJNI.findStemWord(word, SWIGTYPE_p_fsm.getCPtr(net));
  }

  public static void destroyFomaFile(SWIGTYPE_p_fsm net) {
    FomaWrapperJNI.destroyFomaFile(SWIGTYPE_p_fsm.getCPtr(net));
  }

}
