SELECT cpn.CUSTOMER_ID,
  cpn.PRODUCT_ID,
  SUM(cpn.AMOUNT)  "AMOUNT",
  cpn.SHOP_CATEGORY_ID,
  sum(cpn.ORDER_COUNT) "ORDER_COUNT"
FROM CUSTOMER_PRODUCTS cpn
GROUP BY cpn.CUSTOMER_ID,
cpn.PRODUCT_ID,
cpn.SHOP_CATEGORY_ID
ORDER BY cpn.PRODUCT_ID
