/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.apache.lucene.analysis.tr;

public class FomaWrapperJNI {
  public final static native long openFomaFile(String jarg1);
  public final static native String findStemWord(String jarg1, long jarg2);
  public final static native void destroyFomaFile(long jarg1);
}
