/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.apache.lucene.analysis.tr;

public class SWIGTYPE_p_fsm {
  private transient long swigCPtr;

  protected SWIGTYPE_p_fsm(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_fsm() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_fsm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

