SELECT cpn.CUSTOMER_ID,
  cpn.PRODUCT_ID,
  SUM(cpn.AMOUNT)  "AMOUNT",
  cpn.SHOP_CATEGORY_ID,
  sum(cpn.ORDER_COUNT) "ORDER_COUNT",
  csm.SEGMENT_ID
FROM CUSTOMER_PRODUCTS_NEW cpn,
  CUSTOMER_SEGMENT_MEMBERS csm
WHERE cpn.CUSTOMER_ID = csm.CUSTOMER_ID
GROUP BY cpn.CUSTOMER_ID,
cpn.PRODUCT_ID,
cpn.SHOP_CATEGORY_ID,
csm.SEGMENT_ID
ORDER BY cpn.PRODUCT_ID
