SELECT p.PRODUCT_ID,
  cf.CUSTOMER_ID
FROM CUSTOMER_FAVORITES cf,
  PRODUCT_MODELS pmd,
  PRODUCTS p
WHERE cf.PRODUCT_MODEL_ID = pmd.PRODUCT_MODEL_ID
AND p.PRODUCT_MODEL_ID    = pmd.PRODUCT_MODEL_ID

