SELECT p.PRODUCT_ID,
  features.FEATURE_VALUE,
   pmd.PRODUCT_MODEL_ID
FROM  PRODUCT_MODEL_FEATURES features,
  PRODUCT_MODELS pmd,
  PRODUCTS p
WHERE features.PRODUCT_MODEL_ID = pmd.PRODUCT_MODEL_ID
AND p.PRODUCT_MODEL_ID    = pmd.PRODUCT_MODEL_ID
