SELECT p.PRODUCT_ID, 
  pmp.product_model_id,
  props.PROPERTY_NAME,
  props.TYPE "PROPERTY_TYPE"
FROM PROPERTIES props,
  PRODUCT_MODEL_PROPERTIES pmp,
  PRODUCTS p,
  PRODUCT_MODELS pmd
WHERE props.PROPERTY_ID = pmp.PROPERTY_ID
 AND   pmp.PRODUCT_MODEL_ID = pmd.PRODUCT_MODEL_ID
AND p.PRODUCT_MODEL_ID    = pmd.PRODUCT_MODEL_ID
