SELECT p.PRODUCT_ID,
  cf.CUSTOMER_ID
FROM KANGURUM.CUSTOMER_FAVORITES cf,
  KANGURUM.PRODUCT_MODELS pmd,
  KANGURUM.PRODUCTS p
WHERE cf.PRODUCT_MODEL_ID = pmd.PRODUCT_MODEL_ID
AND p.PRODUCT_MODEL_ID    = pmd.PRODUCT_MODEL_ID

