SELECT p.PRODUCT_ID,
  features.FEATURE_VALUE,
   pmd.PRODUCT_MODEL_ID
FROM  KANGURUM.PRODUCT_MODEL_FEATURES features,
  KANGURUM.PRODUCT_MODELS pmd,
  KANGURUM.PRODUCTS p
WHERE features.PRODUCT_MODEL_ID = pmd.PRODUCT_MODEL_ID
AND p.PRODUCT_MODEL_ID    = pmd.PRODUCT_MODEL_ID
