./post.sh solrinputfiles/batches/solrinput0.xml&
./post.sh solrinputfiles/batches/solrinput1.xml&
./post.sh solrinputfiles/batches/solrinput2.xml&
./post.sh solrinputfiles/batches/solrinput3.xml&
./post.sh solrinputfiles/batches/solrinput4.xml&
./post.sh solrinputfiles/batches/solrinput5.xml&
./post.sh solrinputfiles/batches/solrinput6.xml&
./post.sh solrinputfiles/batches/solrinput7.xml&
./post.sh solrinputfiles/batches/solrinput8.xml&
./post.sh solrinputfiles/batches/solrinput9.xml&
./post.sh solrinputfiles/batches/solrinput10.xml&
./post.sh solrinputfiles/batches/solrinput11.xml&
./post.sh solrinputfiles/batches/solrinput12.xml&
./post.sh solrinputfiles/batches/solrinput13.xml&
./post.sh solrinputfiles/batches/solrinput14.xml&
./post.sh solrinputfiles/batches/solrinput15.xml&
./post.sh solrinputfiles/batches/solrinput16.xml&
./post.sh solrinputfiles/batches/solrinput17.xml&
./post.sh solrinputfiles/batches/solrinput18.xml&
./post.sh solrinputfiles/batches/solrinput19.xml&
./post.sh solrinputfiles/batches/solrinput20.xml&
./post.sh solrinputfiles/batches/solrinput21.xml&
./post.sh solrinputfiles/batches/solrinput22.xml&
./post.sh solrinputfiles/batches/solrinput23.xml&
