SELECT cpn.CUSTOMER_ID,
  cpn.PRODUCT_ID,
  SUM(cpn.AMOUNT)  "AMOUNT",
  cpn.SHOP_CATEGORY_ID,
  cast(0 as NUMBER(19,0)) AS "ORDER_COUNT"
FROM MACROCENTER.CUSTOMER_PRODUCTS cpn
GROUP BY cpn.CUSTOMER_ID,
cpn.PRODUCT_ID,
cpn.SHOP_CATEGORY_ID
ORDER BY cpn.PRODUCT_ID
