SELECT
    psi.PRODUCT_SALES_INFO_ID
FROM
    MACROCENTER.PRODUCT_SALES_INFOS psi,
    MACROCENTER.PRODUCT_SALES_INFO_DISCOUNTS psid,
    MACROCENTER.DISCOUNTS d
WHERE
    psi.PRODUCT_SALES_INFO_ID = psid.PRODUCT_SALES_INFO_ID
AND d.DISCOUNT_ID = psid.DISCOUNT_ID
AND d.ACTIVE = 1
AND d.START_DATE <= to_date('EDATE','yyyy-mm-dd')
AND d.END_DATE >= to_date('EDATE','yyyy-mm-dd')
