SELECT p.PRODUCT_ID,
  cf.CUSTOMER_ID
FROM MACROCENTER.CUSTOMER_FAVORITES cf,
  MACROCENTER.PRODUCT_MODELS pmd,
  MACROCENTER.PRODUCTS p
WHERE cf.PRODUCT_MODEL_ID = pmd.PRODUCT_MODEL_ID
AND p.PRODUCT_MODEL_ID    = pmd.PRODUCT_MODEL_ID

