SELECT p.PRODUCT_ID,
  features.FEATURE_VALUE,
   pmd.PRODUCT_MODEL_ID
FROM  MACROCENTER.PRODUCT_MODEL_FEATURES features,
  MACROCENTER.PRODUCT_MODELS pmd,
  MACROCENTER.PRODUCTS p
WHERE features.PRODUCT_MODEL_ID = pmd.PRODUCT_MODEL_ID
AND p.PRODUCT_MODEL_ID    = pmd.PRODUCT_MODEL_ID
