SELECT seg.SON_SEGMENT,
  SUM(it.PRODUCT_QUANTITY_SUM) "Amount",
  SUM(it.PRODUCT_TRANS_COUNT) "OrderCount"
FROM CRM.SPSS_VM_KART_ITEM it,CRM.SPSS_VM_SEGMENT seg
where seg.MIGROSCARDNUMBER = it.MIGROSCARDNUMBER
GROUP BY seg.SON_SEGMENT
