SELECT cpn.CUSTOMER_ID,
  cpn.PRODUCT_ID,
  cpn.AMOUNT,
  cpn.SHOP_CATEGORY_ID,
  cpn.ORDER_COUNT,
  csm.SEGMENT_ID
FROM CUSTOMER_PRODUCTS_NEW cpn,
  CUSTOMER_SEGMENT_MEMBERS csm
WHERE cpn.CUSTOMER_ID = csm.CUSTOMER_ID
